
        // Store configuration
        const STORE_CONFIG = {
            whatsappNumber: '212636487541',
            currency: '€',
            siteName: 'Gaming Community',
            siteUrl: 'https://simo4564.github.io/xbox-gaming-hub/'
        };

        // --- FALLBACK DATA ---
        // This simulates the data generated by the Node.js scraper.
        // It guarantees the site runs beautifully immediately without a backend.
        const fallbackProducts = [
            { id: 'gpu-1m', name: 'Xbox Game Pass Ultimate - 1 Month', category: 'subscriptions', price: 10.99, oldPrice: 14.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Xbox%20Game%20Pass%20new%20logo%20-%20colored%20version.svg', badge: 'Best Seller', description: 'Play hundreds of high-quality games on console, PC, and cloud. Includes EA Play.', inStock: true },
            { id: 'gpu-3m', name: 'Xbox Game Pass Ultimate - 3 Months', category: 'subscriptions', price: 28.50, oldPrice: 44.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Xbox%20Game%20Pass%20new%20logo%20-%20colored%20version.svg', badge: 'Hot Deal', description: '3 months of Ultimate access. Play day one releases and enjoy multiplayer.', inStock: true },
            { id: 'gpc-12m', name: 'Xbox Game Pass Core - 12 Months', category: 'subscriptions', price: 42.90, oldPrice: 59.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Xbox%20Game%20Pass%20logo%20-%20colored%20version.svg', badge: '', description: 'Formerly Xbox Live Gold. Online console multiplayer and catalog of 25+ games.', inStock: true },
            { id: 'gift-10', name: 'Xbox Gift Card 10 EUR', category: 'giftcards', price: 9.50, oldPrice: 10.00, image: 'assets/gift-card-10-eur.png?v=4', badge: '', description: 'Add funds to your Microsoft account. Buy games, add-ons, and more.', inStock: true },
            { id: 'gift-20', name: 'Xbox Gift Card 20 EUR', category: 'giftcards', price: 18.80, oldPrice: 20.00, image: 'assets/gift-card-20-eur.png?v=4', badge: '', description: 'Add funds to your Microsoft account. Buy games, add-ons, and more.', inStock: true },
            { id: 'gift-50', name: 'Xbox Gift Card 50 EUR', category: 'giftcards', price: 46.50, oldPrice: 50.00, image: 'assets/gift-card-50-eur.png?v=4', badge: 'Save 7%', description: 'Perfect for buying full-priced games or expanding your library.', inStock: true },
            { id: 'game-fc25', name: 'EA Sports FC 25 (Xbox One & Series X|S)', category: 'games', price: 54.90, oldPrice: 79.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fc-25-logo.png', badge: 'New', description: 'Experience the most true-to-life football experience ever.', inStock: true },
            { id: 'game-cod6', name: 'Call of Duty: Black Ops 6 (Cross-Gen)', category: 'games', price: 62.00, oldPrice: 79.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Call%20of%20Duty%20-%20Black%20Ops%206%20Logo.svg', badge: 'Trending', description: 'The signature Black Ops series returns with an epic campaign and multiplayer.', inStock: true },
            { id: 'game-fh5', name: 'Forza Horizon 5 Standard Edition', category: 'games', price: 24.50, oldPrice: 69.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Forza_Horizon_5_gameplays.jpg', badge: '', description: 'Explore the vibrant and ever-evolving open world landscapes of Mexico.', inStock: true },
            { id: 'game-gta5', name: 'Grand Theft Auto V Premium Edition', category: 'games', price: 12.90, oldPrice: 29.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Theft%20Auto%20logo%20%28since%202003%29.png', badge: 'Must Have', description: 'Includes GTA V Story Mode and Grand Theft Auto Online.', inStock: true },
            { id: 'game-mc', name: 'Minecraft (Xbox)', category: 'games', price: 16.50, oldPrice: 19.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Minecraft%20Classic%20screenshot.jpg', badge: '', description: 'Explore randomly generated worlds and build amazing things.', inStock: true },
            { id: 'game-cyber', name: 'Cyberpunk 2077', category: 'games', price: 28.00, oldPrice: 59.99, image: 'https://commons.wikimedia.org/wiki/Special:FilePath/CP2077LOGO.jpg', badge: '', description: 'An open-world, action-adventure RPG set in the dark future of Night City.', inStock: true }
        ];

        // State
        let products = [];
        let cart = JSON.parse(localStorage.getItem('gc_cart')) || [];
        let favorites = JSON.parse(localStorage.getItem('gc_favorites')) || [];
        let recentlyViewed = JSON.parse(localStorage.getItem('gc_recent')) || [];
        let compareItems = JSON.parse(localStorage.getItem('gc_compare')) || [];
        let currentFilter = 'all';
        let currentSort = 'popular';
        let searchQuery = '';

        // DOM Elements
        const grid = document.getElementById('product-grid');
        const emptyState = document.getElementById('empty-state');
        const featuredDealsGrid = document.getElementById('featured-deals-grid');
        const recentlyViewedSection = document.getElementById('recently-viewed-section');
        const recentlyViewedGrid = document.getElementById('recently-viewed-grid');
        const cartCount = document.getElementById('cart-count');
        const favoritesCount = document.getElementById('favorites-count');
        const cartItemsContainer = document.getElementById('cart-items');
        const cartSubtotal = document.getElementById('cart-subtotal');
        const cartTotal = document.getElementById('cart-total');
        const cartDrawer = document.getElementById('cart-drawer');
        const cartPanel = document.getElementById('cart-panel');
        const cartOverlay = document.getElementById('cart-overlay');
        const checkoutFields = document.getElementById('checkout-fields');
        const compareTray = document.getElementById('compare-tray');
        const compareCount = document.getElementById('compare-count');
        const comparePreview = document.getElementById('compare-preview');
        const compareModal = document.getElementById('compare-modal');
        const compareModalContent = document.getElementById('compare-modal-content');
        const compareModalBody = document.getElementById('compare-modal-body');

        // Initialization
        async function init() {
            setYear();
            setupEventListeners();
            await loadProducts();
            renderFeaturedDeals();
            renderProducts();
            renderRecentlyViewed();
            updateCartUI();
            updateFavoritesUI();
            renderCompareTray();
            initScrollAnimations();
            setLastUpdated();
            startCountdown();
        }

        // Set Copyright Year
        function setYear() {
            document.getElementById('year').textContent = new Date().getFullYear();
        }

        // Load Products (Try external JSON, fallback to local)
        async function loadProducts() {
            try {
                // Attempt to fetch from the file updated by Node.js
                const res = await fetch('products.json');
                if(!res.ok) throw new Error('Network response was not ok');
                const data = await res.json();
                // Normalize pricing fields to match expected keys
                products = data.map(p => ({
                    ...p,
                    price: Number(p.price ?? p.finalPrice ?? 0),
                    oldPrice: p.oldPrice ? Number(p.oldPrice) : null,
                }));
            } catch (e) {
                console.warn("Could not load products.json, using fallback data. This is normal if running locally without a server.");
                products = fallbackProducts;
            }
        }

        // Event Listeners Setup
        function setupEventListeners() {
            // Cart Toggles
            document.getElementById('cart-btn').addEventListener('click', openCart);
            document.getElementById('favorites-btn').addEventListener('click', () => {
                currentFilter = 'favorites';
                setActiveCategoryButton('favorites');
                document.getElementById('store').scrollIntoView({ behavior: 'smooth', block: 'start' });
                renderProducts();
            });
            document.getElementById('close-cart-btn').addEventListener('click', closeCart);
            document.getElementById('cart-overlay').addEventListener('click', closeCart);
            
            // Mobile Menu
            const mobileBtn = document.getElementById('mobile-menu-btn');
            const mobileMenu = document.getElementById('mobile-menu');
            mobileBtn.addEventListener('click', () => {
                mobileMenu.classList.toggle('hidden');
            });
            document.querySelectorAll('.mobile-link').forEach(link => {
                link.addEventListener('click', () => mobileMenu.classList.add('hidden'));
            });

            // Filters & Sort
            document.querySelectorAll('.cat-btn').forEach(btn => {
                btn.addEventListener('click', (e) => {
                    currentFilter = e.target.dataset.cat;
                    setActiveCategoryButton(currentFilter);
                    renderProducts();
                });
            });

            const searchInput = document.getElementById('search-input');
            const clearSearchBtn = document.getElementById('clear-search-btn');
            const backToTopBtn = document.getElementById('back-to-top');

            searchInput.addEventListener('input', (e) => {
                searchQuery = e.target.value.toLowerCase();
                if (e.target.value.length > 0) {
                    clearSearchBtn.classList.remove('hidden');
                } else {
                    clearSearchBtn.classList.add('hidden');
                }
                renderProducts();
            });

            clearSearchBtn.addEventListener('click', () => {
                searchInput.value = '';
                searchQuery = '';
                clearSearchBtn.classList.add('hidden');
                renderProducts();
            });

            document.getElementById('sort-select').addEventListener('change', (e) => {
                currentSort = e.target.value;
                renderProducts();
            });

            // Sticky Nav logic
            window.addEventListener('scroll', () => {
                const nav = document.getElementById('navbar');
                if (window.scrollY > 20) {
                    nav.classList.add('shadow-lg');
                } else {
                    nav.classList.remove('shadow-lg');
                }
                if (window.scrollY > 300) {
                    backToTopBtn.classList.remove('opacity-0', 'pointer-events-none');
                } else {
                    backToTopBtn.classList.add('opacity-0', 'pointer-events-none');
                }
            });

            backToTopBtn.addEventListener('click', () => {
                window.scrollTo({ top: 0, behavior: 'smooth' });
            });

            // FAQ Accordion
            document.querySelectorAll('.faq-btn').forEach(btn => {
                btn.addEventListener('click', () => {
                    const content = btn.nextElementSibling;
                    const icon = btn.querySelector('i');
                    content.classList.toggle('hidden');
                    icon.classList.toggle('rotate-180');
                });
            });

            // Checkout
            document.getElementById('checkout-btn').addEventListener('click', handleCheckout);
            
            // Modal Close
            document.getElementById('close-modal-btn').addEventListener('click', closeProductModal);
            document.getElementById('product-modal-overlay').addEventListener('click', closeProductModal);
            document.getElementById('open-compare-btn').addEventListener('click', openCompareModal);
            document.getElementById('clear-compare-btn').addEventListener('click', clearCompare);
            document.getElementById('close-compare-btn').addEventListener('click', closeCompareModal);
            document.getElementById('compare-modal-overlay').addEventListener('click', closeCompareModal);

            // Escape key close for cart and modal
            document.addEventListener('keydown', (e) => {
                if (e.key === 'Escape') {
                    closeCart();
                    closeProductModal();
                    closeCompareModal();
                }
            });
        }

        function setActiveCategoryButton(category) {
            document.querySelectorAll('.cat-btn').forEach(b => {
                b.classList.remove('bg-brand/20', 'border-brand', 'text-brand');
                b.classList.add('bg-dark-card', 'border-dark-border', 'text-gray-400');
            });
            const activeBtn = document.querySelector(`.cat-btn[data-cat="${category}"]`);
            if (activeBtn) {
                activeBtn.classList.remove('bg-dark-card', 'border-dark-border', 'text-gray-400');
                activeBtn.classList.add('bg-brand/20', 'border-brand', 'text-brand');
            }
        }

        // Core Render Function
        function renderProducts() {
            let filtered = products.filter(p => {
                const matchCat = currentFilter === 'all' || p.category === currentFilter || (currentFilter === 'favorites' && favorites.includes(p.id));
                const matchSearch = p.name.toLowerCase().includes(searchQuery) || p.description.toLowerCase().includes(searchQuery);
                return matchCat && matchSearch;
            });

            // Sorting
            if (currentSort === 'price-low') filtered.sort((a, b) => a.price - b.price);
            else if (currentSort === 'price-high') filtered.sort((a, b) => b.price - a.price);
            else if (currentSort === 'name') filtered.sort((a, b) => a.name.localeCompare(b.name));
            // 'popular' keeps default array order

            grid.innerHTML = '';
            
            if (filtered.length === 0) {
                emptyState.classList.remove('hidden');
            } else {
                emptyState.classList.add('hidden');
                filtered.forEach(p => {
                    const discount = p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;
                    const isFavorite = favorites.includes(p.id);
                    const card = document.createElement('div');
                    card.className = 'glass-card rounded-xl overflow-hidden hover-lift flex flex-col h-full animate-fade-in group';
                    card.innerHTML = `
                        <div class="relative cursor-pointer overflow-hidden aspect-[3/4]" onclick="openProductModal('${p.id}')">
                            <img src="${p.image}" alt="${p.name}" loading="lazy" class="w-full h-full object-contain bg-black/20 p-4 group-hover:scale-105 transition-transform duration-500">
                            ${p.badge ? `<div class="absolute top-3 left-3 bg-brand text-white text-[10px] font-bold px-2 py-1 rounded shadow-lg uppercase tracking-wider">${p.badge}</div>` : ''}
                            ${discount > 0 && !p.badge ? `<div class="absolute top-3 left-3 bg-red-600 text-white text-[10px] font-bold px-2 py-1 rounded shadow-lg uppercase tracking-wider">-${discount}%</div>` : ''}
                            <button onclick="toggleFavorite(event, '${p.id}')" class="absolute top-3 right-3 w-10 h-10 rounded-full border ${isFavorite ? 'border-brand bg-brand/20 text-brand' : 'border-white/10 bg-black/40 text-white'} backdrop-blur-md flex items-center justify-center hover:scale-105 transition-all" aria-label="Save to favorites">
                                <i class="ph ${isFavorite ? 'ph-fill' : ''} ph-heart text-lg"></i>
                            </button>
                            
                            <!-- Hover Overlay -->
                            <div class="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                                <span class="bg-white/20 backdrop-blur-md text-white px-4 py-2 rounded-full text-sm font-medium flex items-center gap-2">
                                    <i class="ph ph-eye"></i> Quick View
                                </span>
                            </div>
                        </div>
                        <div class="p-5 flex flex-col flex-1">
                            <h3 class="font-bold text-white mb-1 line-clamp-2 leading-tight cursor-pointer hover:text-brand transition-colors" onclick="openProductModal('${p.id}')">${p.name}</h3>
                            <div class="flex items-center gap-1 text-yellow-400 mb-2" aria-label="Rating">
                                <i class="ph-fill ph-star"></i>
                                <i class="ph-fill ph-star"></i>
                                <i class="ph-fill ph-star"></i>
                                <i class="ph-fill ph-star"></i>
                                <i class="ph-fill ph-star"></i>
                            </div>
                            <div class="flex items-center gap-2 mb-4 mt-auto pt-4">
                                <span class="text-xl font-bold text-brand">${STORE_CONFIG.currency}${p.price.toFixed(2)}</span>
                                ${p.oldPrice ? `<span class="text-sm text-gray-500 line-through">${STORE_CONFIG.currency}${p.oldPrice.toFixed(2)}</span>` : ''}
                            </div>
                            <div class="grid grid-cols-2 gap-2">
                                <button onclick="addToCart('${p.id}')" class="w-full bg-dark-bg hover:bg-brand border border-dark-border hover:border-brand text-white font-medium py-2.5 rounded-lg transition-all flex justify-center items-center gap-2 group/btn" aria-label="Add to cart">
                                    <i class="ph ph-shopping-cart-simple group-hover/btn:animate-bounce"></i> Add to Cart
                                </button>
                                <button onclick="toggleCompare(event, '${p.id}')" class="w-full bg-white/5 hover:bg-white/10 border border-dark-border hover:border-brand text-white font-medium py-2.5 rounded-lg transition-all flex justify-center items-center gap-2" aria-label="Compare product">
                                    <i class="ph ph-scales"></i> Compare
                                </button>
                            </div>
                        </div>
                    `;
                    grid.appendChild(card);
                });
            }
        }

        // Product Modal Logic
        function openProductModal(id) {
            const p = products.find(x => x.id === id);
            if(!p) return;
            addToRecentlyViewed(id);
            
            const modalBody = document.getElementById('product-modal-body');
            const discount = p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;
            const isFavorite = favorites.includes(p.id);
            
            modalBody.innerHTML = `
                <div class="bg-dark-bg p-6 flex items-center justify-center relative">
                    <img src="${p.image}" alt="${p.name}" loading="lazy" class="max-w-full max-h-[400px] object-contain rounded-xl shadow-2xl bg-black/20 p-4">
                    ${p.badge ? `<div class="absolute top-6 left-6 bg-brand text-white text-xs font-bold px-3 py-1.5 rounded uppercase tracking-wider">${p.badge}</div>` : ''}
                    <button onclick="toggleFavorite(event, '${p.id}'); openProductModal('${p.id}')" class="absolute top-6 right-6 w-10 h-10 rounded-full border ${isFavorite ? 'border-brand bg-brand/20 text-brand' : 'border-white/10 bg-black/40 text-white'} backdrop-blur-md flex items-center justify-center hover:scale-105 transition-all" aria-label="Save to favorites">
                        <i class="ph ${isFavorite ? 'ph-fill' : ''} ph-heart text-lg"></i>
                    </button>
                </div>
                <div class="p-8 flex flex-col justify-center">
                    <div class="text-xs text-brand font-bold uppercase tracking-widest mb-2">${p.category}</div>
                    <h2 class="text-2xl font-bold text-white mb-2 leading-tight">${p.name}</h2>
                    <div class="flex items-center gap-1 text-yellow-400 mb-4" aria-label="Rating">
                        <i class="ph-fill ph-star"></i>
                        <i class="ph-fill ph-star"></i>
                        <i class="ph-fill ph-star"></i>
                        <i class="ph-fill ph-star"></i>
                        <i class="ph-fill ph-star"></i>
                    </div>
                    <p class="text-gray-400 mb-6 leading-relaxed">${p.description}</p>
                    
                    <div class="flex items-end gap-3 mb-6">
                        <span class="text-3xl font-bold text-white">${STORE_CONFIG.currency}${p.price.toFixed(2)}</span>
                        ${p.oldPrice ? `<span class="text-lg text-gray-500 line-through mb-1">${STORE_CONFIG.currency}${p.oldPrice.toFixed(2)}</span> <span class="text-green-500 text-sm mb-1 font-medium">Save ${discount}%</span>` : ''}
                    </div>
                    
                    <div class="flex items-center gap-3 mb-8 text-sm text-gray-400">
                        <div class="flex items-center gap-1"><i class="ph-fill ph-lightning text-yellow-500"></i> Instant Delivery</div>
                        <span>•</span>
                        <div class="flex items-center gap-1"><i class="ph-fill ph-globe text-blue-400"></i> Global Region</div>
                    </div>
                    
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <button onclick="addToCart('${p.id}'); closeProductModal();" class="w-full bg-brand hover:bg-brand-light text-white font-bold py-4 rounded-xl transition-all shadow-[0_0_20px_rgba(16,124,16,0.3)] flex justify-center items-center gap-2 text-lg" aria-label="Add to cart">
                            <i class="ph ph-shopping-cart-simple text-xl"></i> Add to Cart
                        </button>
                        <button onclick="toggleCompare(event, '${p.id}')" class="w-full bg-dark-bg hover:bg-white/10 border border-dark-border hover:border-brand text-white font-bold py-4 rounded-xl transition-all flex justify-center items-center gap-2 text-lg" aria-label="Compare product">
                            <i class="ph ph-scales text-xl"></i> Compare
                        </button>
                    </div>
                </div>
            `;
            
            const modal = document.getElementById('product-modal');
            const content = document.getElementById('product-modal-content');
            
            modal.classList.remove('hidden');
            // Small delay to allow display:block to apply before animating opacity
            setTimeout(() => {
                modal.classList.remove('pointer-events-none');
                content.classList.remove('scale-95', 'opacity-0');
                content.classList.add('scale-100', 'opacity-100');
            }, 10);
        }

        function closeProductModal() {
            const modal = document.getElementById('product-modal');
            const content = document.getElementById('product-modal-content');
            
            content.classList.remove('scale-100', 'opacity-100');
            content.classList.add('scale-95', 'opacity-0');
            modal.classList.add('pointer-events-none');
            
            setTimeout(() => {
                modal.classList.add('hidden');
            }, 300);
        }

        function toggleFavorite(event, id) {
            if (event) event.stopPropagation();
            if (favorites.includes(id)) {
                favorites = favorites.filter(item => item !== id);
            } else {
                favorites.unshift(id);
            }
            localStorage.setItem('gc_favorites', JSON.stringify(favorites));
            updateFavoritesUI();
            renderCompareTray();
            renderProducts();
            renderRecentlyViewed();
        }

        function updateFavoritesUI() {
            if (favorites.length > 0) {
                favoritesCount.textContent = favorites.length;
                favoritesCount.classList.remove('hidden');
            } else {
                favoritesCount.classList.add('hidden');
            }
        }

        function addToRecentlyViewed(id) {
            recentlyViewed = [id, ...recentlyViewed.filter(item => item !== id)].slice(0, 4);
            localStorage.setItem('gc_recent', JSON.stringify(recentlyViewed));
            renderRecentlyViewed();
        }

        function renderFeaturedDeals() {
            if (!featuredDealsGrid) return;
            const offerEntries = Object.values(window.OFFER_DETAILS || {})
                .map((offer) => ({ offer, product: products.find((item) => item.id === offer.productId) }))
                .filter((entry) => entry.product)
                .slice(0, 3);

            if (offerEntries.length === 0) {
                featuredDealsGrid.innerHTML = '';
                return;
            }

            featuredDealsGrid.innerHTML = offerEntries.map(({ offer, product }, index) => {
                const savings = product.oldPrice ? Math.round(((product.oldPrice - product.price) / product.oldPrice) * 100) : 0;
                return `
                    <article class="glass-card rounded-2xl overflow-hidden border border-dark-border hover-lift reveal" style="transition-delay:${index * 100}ms;">
                        <a href="offer.html?slug=${offer.slug}" class="block aspect-[16/10] overflow-hidden">
                            <img src="${offer.image}" alt="${offer.imageAlt}" loading="lazy" class="w-full h-full object-cover transition-transform duration-500 hover:scale-105">
                        </a>
                        <div class="p-6">
                            <div class="flex items-start justify-between gap-4 mb-5">
                                <div>
                                    <span class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand/10 border border-brand/30 text-brand text-xs font-semibold uppercase tracking-[0.18em]">${offer.kicker}</span>
                                    <h3 class="text-2xl font-bold text-white mt-4 leading-tight">${offer.title}</h3>
                                </div>
                                <span class="text-xs font-bold px-3 py-2 rounded-full ${savings > 0 ? 'bg-red-600/20 text-red-300 border border-red-600/30' : 'bg-white/5 text-gray-300 border border-white/10'}">${offer.badge || (savings > 0 ? `Save ${savings}%` : 'Hot now')}</span>
                            </div>
                            <p class="text-gray-400 mb-6 line-clamp-3">${offer.shortDescription}</p>
                            <div class="flex items-end gap-3 mb-6">
                                <span class="text-3xl font-bold text-white">${STORE_CONFIG.currency}${product.price.toFixed(2)}</span>
                                ${product.oldPrice ? `<span class="text-gray-500 line-through">${STORE_CONFIG.currency}${product.oldPrice.toFixed(2)}</span>` : ''}
                            </div>
                            <div class="flex gap-3">
                                <a href="offer.html?slug=${offer.slug}" class="flex-1 bg-brand hover:bg-brand-light text-white font-semibold py-3 rounded-xl transition-colors text-center">Open offer page</a>
                                <button onclick="addToCart('${product.id}')" class="px-4 py-3 rounded-xl border border-dark-border hover:border-brand text-white transition-colors" aria-label="Add featured deal to cart"><i class="ph ph-shopping-cart-simple"></i></button>
                            </div>
                        </div>
                    </article>
                `;
            }).join('');
        }

        function renderRecentlyViewed() {
            if (!recentlyViewedSection || !recentlyViewedGrid) return;
            const viewedProducts = recentlyViewed
                .map(id => products.find(p => p.id === id))
                .filter(Boolean);
            if (viewedProducts.length === 0) {
                recentlyViewedSection.classList.add('hidden');
                recentlyViewedGrid.innerHTML = '';
                return;
            }
            recentlyViewedSection.classList.remove('hidden');
            recentlyViewedGrid.innerHTML = viewedProducts.map((p) => `
                <div class="glass-card rounded-xl overflow-hidden border border-dark-border hover-lift flex flex-col h-full">
                    <div class="relative cursor-pointer overflow-hidden aspect-[3/4]" onclick="openProductModal('${p.id}')">
                        <img src="${p.image}" alt="${p.name}" loading="lazy" class="w-full h-full object-cover">
                    </div>
                    <div class="p-5 flex flex-col flex-1">
                        <h3 class="font-bold text-white mb-2 line-clamp-2">${p.name}</h3>
                        <div class="flex items-center gap-2 mb-4 mt-auto">
                            <span class="text-xl font-bold text-brand">${STORE_CONFIG.currency}${p.price.toFixed(2)}</span>
                            ${p.oldPrice ? `<span class="text-sm text-gray-500 line-through">${STORE_CONFIG.currency}${p.oldPrice.toFixed(2)}</span>` : ''}
                        </div>
                        <div class="flex gap-2">
                            <button onclick="openProductModal('${p.id}')" class="flex-1 bg-dark-bg hover:bg-brand border border-dark-border hover:border-brand text-white font-medium py-2.5 rounded-lg transition-all">Quick View</button>
                            <button onclick="addToCart('${p.id}')" class="px-4 py-2.5 rounded-lg border border-dark-border hover:border-brand text-white transition-all" aria-label="Add to cart"><i class="ph ph-shopping-cart-simple"></i></button>
                        </div>
                    </div>
                </div>
            `).join('');
        }

        function toggleCompare(event, id) {
            if (event) event.stopPropagation();
            if (compareItems.includes(id)) {
                compareItems = compareItems.filter(item => item !== id);
            } else {
                if (compareItems.length >= 3) {
                    showToast('Compare limit reached', 'Remove one product before adding another to compare.');
                    return;
                }
                compareItems.push(id);
            }
            localStorage.setItem('gc_compare', JSON.stringify(compareItems));
            renderCompareTray();
            renderProducts();
        }

        function renderCompareTray() {
            if (!compareTray) return;
            compareCount.textContent = compareItems.length;
            if (compareItems.length === 0) {
                compareTray.classList.add('opacity-0', 'pointer-events-none');
                comparePreview.textContent = 'Choose up to 3 products to compare price, region fit, and delivery notes.';
                return;
            }
            compareTray.classList.remove('opacity-0', 'pointer-events-none');
            const names = compareItems
                .map(id => products.find(p => p.id === id))
                .filter(Boolean)
                .map(p => p.name)
                .slice(0, 3);
            comparePreview.textContent = names.join(' • ');
        }

        function clearCompare() {
            compareItems = [];
            localStorage.setItem('gc_compare', JSON.stringify(compareItems));
            renderCompareTray();
            renderProducts();
            closeCompareModal();
        }

        function openCompareModal() {
            if (compareItems.length === 0) return;
            const compareProducts = compareItems
                .map(id => products.find(p => p.id === id))
                .filter(Boolean);
            compareModalBody.innerHTML = `
                <div class="mb-6 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                    <p class="text-gray-400 max-w-2xl">Use this quick comparison to choose the right product faster. When you’re ready, add the best match to your cart and continue checkout through WhatsApp.</p>
                    <div class="inline-flex items-center gap-2 text-sm text-gray-400"><i class="ph ph-info text-brand"></i> Maximum 3 products</div>
                </div>
                <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
                    ${compareProducts.map((p) => {
                        const discount = p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;
                        const regionHint = p.category === 'giftcards' ? 'Check store region before redeeming' : (p.category === 'subscriptions' ? 'Best for matching Microsoft account region' : 'Check region note with support before redeeming');
                        return `
                            <article class="glass-card rounded-2xl overflow-hidden border border-dark-border flex flex-col">
                                <div class="aspect-[4/3] overflow-hidden bg-dark-bg">
                                    <img src="${p.image}" alt="${p.name}" class="w-full h-full object-cover" loading="lazy">
                                </div>
                                <div class="p-5 flex-1 flex flex-col">
                                    <div class="flex items-start justify-between gap-3 mb-3">
                                        <h4 class="text-lg font-bold text-white leading-tight">${p.name}</h4>
                                        <button onclick="toggleCompare(event, '${p.id}'); openCompareModal();" class="text-gray-500 hover:text-white" aria-label="Remove from compare"><i class="ph ph-x"></i></button>
                                    </div>
                                    <p class="text-xs uppercase tracking-[0.2em] text-brand font-semibold mb-3">${p.category}</p>
                                    <div class="flex items-end gap-2 mb-4">
                                        <span class="text-2xl font-bold text-white">${STORE_CONFIG.currency}${p.price.toFixed(2)}</span>
                                        ${p.oldPrice ? `<span class="text-sm text-gray-500 line-through">${STORE_CONFIG.currency}${p.oldPrice.toFixed(2)}</span>` : ''}
                                        ${discount > 0 ? `<span class="text-xs px-2 py-1 rounded-full bg-red-600/20 text-red-300 border border-red-600/30">Save ${discount}%</span>` : ''}
                                    </div>
                                    <div class="space-y-3 text-sm mb-6">
                                        <div class="bg-dark-bg border border-dark-border rounded-xl p-3">
                                            <p class="text-white font-semibold mb-1">Good for</p>
                                            <p class="text-gray-400">${p.category === 'subscriptions' ? 'Fast access to Game Pass benefits and multiplayer.' : p.category === 'giftcards' ? 'Flexible wallet balance and safer gifting.' : 'Players who want a specific title instantly.'}</p>
                                        </div>
                                        <div class="bg-dark-bg border border-dark-border rounded-xl p-3">
                                            <p class="text-white font-semibold mb-1">Region tip</p>
                                            <p class="text-gray-400">${regionHint}</p>
                                        </div>
                                        <div class="bg-dark-bg border border-dark-border rounded-xl p-3">
                                            <p class="text-white font-semibold mb-1">Delivery</p>
                                            <p class="text-gray-400">Digital code sent through WhatsApp after order confirmation.</p>
                                        </div>
                                    </div>
                                    <div class="mt-auto grid grid-cols-1 sm:grid-cols-2 gap-2">
                                        <button onclick="addToCart('${p.id}')" class="bg-brand hover:bg-brand-light text-white font-semibold py-3 rounded-xl transition-colors">Add to cart</button>
                                        <button onclick="openProductModal('${p.id}'); closeCompareModal();" class="bg-dark-bg hover:bg-white/10 border border-dark-border hover:border-brand text-white font-semibold py-3 rounded-xl transition-colors">Quick view</button>
                                    </div>
                                </div>
                            </article>
                        `;
                    }).join('')}
                </div>
            `;
            compareModal.classList.remove('hidden');
            setTimeout(() => {
                compareModal.classList.remove('pointer-events-none');
                compareModalContent.classList.remove('scale-95', 'opacity-0');
                compareModalContent.classList.add('scale-100', 'opacity-100');
            }, 10);
        }

        function closeCompareModal() {
            if (!compareModal) return;
            compareModalContent.classList.remove('scale-100', 'opacity-100');
            compareModalContent.classList.add('scale-95', 'opacity-0');
            compareModal.classList.add('pointer-events-none');
            setTimeout(() => compareModal.classList.add('hidden'), 300);
        }

        // Cart Logic
        function addToCart(id) {
            const product = products.find(p => p.id === id);
            if (!product) return;

            const existing = cart.find(item => item.id === id);
            if (existing) {
                existing.qty += 1;
            } else {
                cart.push({ ...product, qty: 1 });
            }
            
            saveCart();
            updateCartUI();
            showToast(product.name);
        }

        function updateQty(id, delta) {
            const item = cart.find(i => i.id === id);
            if (item) {
                item.qty += delta;
                if (item.qty <= 0) {
                    cart = cart.filter(i => i.id !== id);
                }
                saveCart();
                updateCartUI();
            }
        }

        function removeFromCart(id) {
            cart = cart.filter(i => i.id !== id);
            saveCart();
            updateCartUI();
        }

        function saveCart() {
            localStorage.setItem('gc_cart', JSON.stringify(cart));
        }

        function updateCartUI() {
            // Count badge
            const count = cart.reduce((sum, item) => sum + item.qty, 0);
            if (count > 0) {
                cartCount.textContent = count;
                cartCount.classList.remove('hidden');
            } else {
                cartCount.classList.add('hidden');
            }

            // Items render
            cartItemsContainer.innerHTML = '';
            let total = 0;

            if (cart.length === 0) {
                cartItemsContainer.innerHTML = `
                    <div class="h-full flex flex-col items-center justify-center text-gray-500 py-10">
                        <i class="ph ph-shopping-cart-simple text-6xl mb-4 opacity-50"></i>
                        <p>Your cart is empty.</p>
                        <button onclick="closeCart(); document.getElementById('store').scrollIntoView();" class="mt-4 text-brand font-medium hover:underline">Continue Shopping</button>
                    </div>
                `;
                checkoutFields.classList.add('hidden');
                document.getElementById('checkout-btn').disabled = true;
                document.getElementById('checkout-btn').classList.add('opacity-50', 'cursor-not-allowed');
            } else {
                checkoutFields.classList.remove('hidden');
                document.getElementById('checkout-btn').disabled = false;
                document.getElementById('checkout-btn').classList.remove('opacity-50', 'cursor-not-allowed');
                
                cart.forEach(item => {
                    const itemTotal = item.price * item.qty;
                    total += itemTotal;
                    
                    const el = document.createElement('div');
                    el.className = 'flex gap-4 bg-dark-bg p-3 rounded-lg border border-dark-border';
                    el.innerHTML = `
                        <img src="${item.image}" class="w-16 h-20 object-contain rounded bg-dark-card p-1">
                        <div class="flex-1 flex flex-col justify-between py-1">
                            <div class="flex justify-between items-start">
                                <h4 class="text-sm font-medium text-white line-clamp-2 pr-2">${item.name}</h4>
                                <button onclick="removeFromCart('${item.id}')" class="text-gray-500 hover:text-red-500 transition-colors"><i class="ph-bold ph-trash"></i></button>
                            </div>
                            <div class="flex justify-between items-center mt-2">
                                <div class="flex items-center bg-dark-card rounded border border-dark-border">
                                    <button onclick="updateQty('${item.id}', -1)" class="px-2 py-1 text-gray-400 hover:text-white transition-colors">-</button>
                                    <span class="px-2 text-sm font-medium w-6 text-center">${item.qty}</span>
                                    <button onclick="updateQty('${item.id}', 1)" class="px-2 py-1 text-gray-400 hover:text-white transition-colors">+</button>
                                </div>
                                <span class="font-bold text-brand">${STORE_CONFIG.currency}${itemTotal.toFixed(2)}</span>
                            </div>
                        </div>
                    `;
                    cartItemsContainer.appendChild(el);
                });
            }

            cartSubtotal.textContent = `${STORE_CONFIG.currency}${total.toFixed(2)}`;
            cartTotal.textContent = `${STORE_CONFIG.currency}${total.toFixed(2)}`;
        }

        // Drawer UI logic
        function openCart() {
            document.body.classList.add('overflow-hidden');
            cartDrawer.classList.remove('pointer-events-none');
            cartOverlay.classList.remove('opacity-0', 'pointer-events-none');
            cartOverlay.classList.add('opacity-100', 'pointer-events-auto');
            cartPanel.classList.remove('translate-x-full');
            cartPanel.classList.add('pointer-events-auto');
        }

        function closeCart() {
            document.body.classList.remove('overflow-hidden');
            cartOverlay.classList.remove('opacity-100', 'pointer-events-auto');
            cartOverlay.classList.add('opacity-0', 'pointer-events-none');
            cartPanel.classList.add('translate-x-full');
            cartPanel.classList.remove('pointer-events-auto');
            setTimeout(() => {
                cartDrawer.classList.add('pointer-events-none');
            }, 300);
        }

        function startCountdown() {
            const daysEl = document.getElementById('countdown-days');
            const hoursEl = document.getElementById('countdown-hours');
            const minutesEl = document.getElementById('countdown-minutes');
            if (!daysEl || !hoursEl || !minutesEl) return;

            const getDeadline = () => {
                const now = new Date();
                const end = new Date(now);
                const daysUntilSunday = (7 - now.getDay()) % 7;
                end.setDate(now.getDate() + daysUntilSunday);
                end.setHours(23, 59, 59, 999);
                return end;
            };

            const updateCountdown = () => {
                const now = new Date();
                const deadline = getDeadline();
                const diff = Math.max(0, deadline - now);
                const totalMinutes = Math.floor(diff / 60000);
                const days = Math.floor(totalMinutes / (60 * 24));
                const hours = Math.floor((totalMinutes % (60 * 24)) / 60);
                const minutes = totalMinutes % 60;
                daysEl.textContent = String(days).padStart(2, '0');
                hoursEl.textContent = String(hours).padStart(2, '0');
                minutesEl.textContent = String(minutes).padStart(2, '0');
            };

            updateCountdown();
            setInterval(updateCountdown, 30000);
        }

        // WhatsApp Checkout Builder
        function handleCheckout() {
            if (cart.length === 0) return;

            const ref = 'GC-' + Math.floor(10000 + Math.random() * 90000);
            const customerName = document.getElementById('checkout-name').value.trim() || '—';
            const note = document.getElementById('checkout-note').value.trim() || '—';
            const region = document.getElementById('checkout-region').value.trim() || '—';
            const language = document.getElementById('checkout-language').value || '—';
            const email = document.getElementById('checkout-email').value.trim() || '—';
            const orderDate = new Date();
            const formattedOrderDate = orderDate.toLocaleString('en-GB', {
                day: '2-digit',
                month: 'short',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
            });
            
            let msg = `*New order request from ${STORE_CONFIG.siteName} website*\n\n`;
            msg += `*Order Reference:* ${ref}\n`;
            msg += `*Order Time:* ${formattedOrderDate}\n`;
            msg += `*Customer Name:* ${customerName}\n`;
            msg += `*Gamer Tag / Region:* ${region}\n`;
            msg += `*Preferred Language:* ${language}\n`;
            msg += `*Delivery Email:* ${email}\n`;
            msg += `*Customer Note:* ${note}\n\n`;
            msg += `*Requested Items:*\n`;
            
            let total = 0;
            cart.forEach(item => {
                const itemTotal = item.price * item.qty;
                msg += `• ${item.name}\n`;
                msg += `  Qty: ${item.qty} | Unit: ${STORE_CONFIG.currency}${item.price.toFixed(2)} | Line: ${STORE_CONFIG.currency}${itemTotal.toFixed(2)}\n`;
                total += itemTotal;
            });
            
            msg += `\n*Order Total:* ${STORE_CONFIG.currency}${total.toFixed(2)}\n`;
            msg += `*Delivery Type:* Digital code / subscription\n`;
            msg += `*Source:* ${STORE_CONFIG.siteUrl}\n\n`;
            msg += `Please confirm availability, final payment instructions, and the estimated delivery time for this order. Thank you.`;

            const encodedMsg = encodeURIComponent(msg);
            const waUrl = `https://wa.me/${STORE_CONFIG.whatsappNumber}?text=${encodedMsg}`;
            
            window.open(waUrl, '_blank');
        }

        // Toast
        function showToast(itemName, customMessage = null) {
            const toast = document.getElementById('toast');
            document.getElementById('toast-msg').textContent = customMessage || `${itemName} added.`;
            
            toast.classList.remove('translate-x-[150%]');
            
            setTimeout(() => {
                toast.classList.add('translate-x-[150%]');
            }, 3000);
        }

        // Scroll Animations using IntersectionObserver
        function initScrollAnimations() {
            const observer = new IntersectionObserver((entries) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('active');
                    }
                });
            }, { threshold: 0.1 });
            
            document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
        }

        // Set Last Updated information based on products data
        function setLastUpdated() {
            // Add a "last updated" element if it doesn't exist yet
            let statusElem = document.getElementById('last-updated');
            if (!statusElem) {
                const container = document.querySelector('#store div > div');
                statusElem = document.createElement('p');
                statusElem.id = 'last-updated';
                statusElem.className = 'text-gray-500 text-sm mt-1';
                container.appendChild(statusElem);
            }
            if (!products || products.length === 0) {
                statusElem.textContent = 'Last updated: using fallback prices';
                return;
            }
            const latest = products
                .map(p => p.lastUpdated)
                .filter(Boolean)
                .sort()
                .pop();
            if (latest) {
                const d = new Date(latest);
                statusElem.textContent = `Last updated: ${d.toLocaleString()}`;
            } else {
                statusElem.textContent = 'Last updated: using fallback prices';
            }
        }

        // Run
        document.addEventListener('DOMContentLoaded', init);
    